### ISSUE TITLE
Make it so link sharing not set properly sends the user an error message

### ISSUE THREAD

**Issue by cansavvy** [FredHutch/loqui#13]
Even though I know I'm supposed to enable link sharing, when using loqui I forgot to do that and was puzzled why it wasn't doing anything. 

Even though the instructions are very clear, people like myself can still forget to enable link sharing. 

Can we create an error message that is sent to the user that tells them "Cannot access video; please enable link sharing for your Google slides" or something like that? 

Otherwise users might be waiting around for awhile if they make that mistake like I did.

**Comment by howardbaek** [comment]
Looks like slide decks with/without General access have the same URL:

Anyone with the link:
https://docs.google.com/presentation/d/1Dw_rBb1hySN_76xh9-x5J2dWF_das9BAUjQigf2fN-E/edit?usp=sharing

Restricted:
https://docs.google.com/presentation/d/1Dw_rBb1hySN_76xh9-x5J2dWF_das9BAUjQigf2fN-E/edit?usp=sharing

**Comment by howardbaek** [comment]
Enabled in commit https://github.com/FredHutch/loqui/commit/bc834e924b247430b73b6f675c279bae470c16ff. 

When you provide a link to an inaccessible Google Slides, the input box will turn yellow and tell you "Please set General access of the slides to 'Anyone with the link'".  You will also not be able to click the "Generate" button.
