### ISSUE TITLE
Need to be able to download subtitles as a txt

### ISSUE THREAD

**Issue by avahoffman** [FredHutch/loqui#14]
While it's nice to add subtitles automatically, YouTube uploads work better if the subtitles are added separately. It also provides the opportunity to edit, especially where we have spelled out an unusual sounding word.

Previously, with Mario, files were exported as txt in [SubRip](https://en.wikipedia.org/wiki/SubRip#SubRip_text_file_format) format. Equivalent function with mario was `mario_subtitles()`.

**Comment by howardbaek** [comment]
I can have it generate srt files. Would that work?

**Comment by avahoffman** [comment]
Yes!

**Comment by howardbaek** [comment]
@avahoffman This is implemented in commit https://github.com/FredHutch/loqui/commit/91b73989053c518c4b7b16ac234b82952ae03e5a . Please let me know if this doesn't work for you, else I'll close this issue.

**Comment by avahoffman** [comment]
Awesome! Testing it now.

**Comment by avahoffman** [comment]
Button looks great!!
<img width="213" alt="image" src="https://github.com/FredHutch/loqui/assets/15618412/dff76bbf-75a7-46b6-953d-2b9bb23d4bc9">

However, it looks like something has happened to the file when I click download:
<img width="373" alt="image" src="https://github.com/FredHutch/loqui/assets/15618412/c9bb6a12-4cd6-427b-8e9d-3b8cc457d263">

**Comment by howardbaek** [comment]
Can you try again? I just clicked "Download Subtitle" and was able to get the .srt file.

**Comment by avahoffman** [comment]
> The error message indicates the browser cannot locate a specific file because it's no longer there. However, in our experience, the most common causes behind the ERR_FILE_NOT_FOUND issue are Chrome extensions. Sometimes, extensions can cause errors with the sites you're trying to visit.

Looks like it might be my ad blocker? Will disable and try again.

**Comment by howardbaek** [comment]
@avahoffman This should be fixed now. Can you try one more time? Thanks.

**Comment by avahoffman** [comment]
@howardbaek yes will try now!

**Comment by avahoffman** [comment]
Perfect!! Thank you @howardbaek !!
