### ISSUE TITLE
About tab

### ISSUE THREAD

**Issue by howardbaek** [FredHutch/loqui#29]
Shorten the 2 paragraphs on the About tab with bullet points:

For ex,

# Introducing Loqui: A Shiny app for Creating Automated Videos

## Overview:

- Open source web application for automated video creation.
- Uses [ari](https://github.com/jhudsl/ari), an R package, for generating videos from text and images.
- Provides an intuitive and user-friendly interface.

## How Loqui Works:

- Inputs: Google Slides URL or Microsoft PowerPoint file.
- Extracts speaker notes from slides and converts them into audio.
- Converts Google Slides to images.
- Generates an mp4 video file with images and corresponding audio.

**Comment by howardbaek** [comment]
What do you think? @cansavvy @carriewright11 @kweav

**Comment by cansavvy** [comment]
This looks great! I always love bullet points. Easier to read in my mind.

**Comment by howardbaek** [comment]
Awesome, I'll file a PR
