### ISSUE TITLE
Get Shiny App account prep as described on SciWiki

### ISSUE THREAD

**Issue by cansavvy** [FredHutch/loqui#5]
Step 1: Let's figure out what we need to post a shinyapp to the Hutch's site. https://sciwiki.fredhutch.org/compdemos/shiny/
Step 2: Make the app work locally 
Step 3: Post the working Shiny app to the Hutch site as described by the above instructions 
Step 4: Share with everyone.

**Comment by howardbaek** [comment]
This is done. https://loqui.fredhutch.org/
